### ISSUE TITLE
make home search buttom more photon

### ISSUE THREAD

**Issue by kkren** [harshilsharma63/firefox-customizations#1]
search buttom in about:home looks outdated, can you make it the same as that one in about:newtab

**Comment by ghost** [comment]
Are you talking about this button? -
![Search button](http://imgur.com/a/GYAxW)

**Comment by kkren** [comment]
i cant see the pic
![default](https://user-images.githubusercontent.com/23287823/29859749-24e3494c-8d96-11e7-8628-b6937dcc6027.png)
im talking about this

**Comment by ghost** [comment]
People at Firefox seem to be already working on making some changes with the button. Last night I git it working  but today some styling got updated and its back to usual. So it doesn't make sense working on this as it won't work for long.

You can fire a bug on Bugzilla to notify the devs about this change request and the'll be able to provide a more permanent solution.

**Comment by ghost** [comment]
@kkren I managed to get it working consistently. However a minor issue exists, that the search button turns black as search suggestions populate.

**Comment by ghost** [comment]
Can you please verify if it works for you?

**Comment by kkren** [comment]
thank you, but I can only verify it when it's Saturday.

**Comment by ghost** [comment]
Saturday works for me.

**Comment by kkren** [comment]
![default](https://user-images.githubusercontent.com/23287823/30215041-28d14a98-94e1-11e7-8c68-c6da607f0e9c.png)
after hover
![default](https://user-images.githubusercontent.com/23287823/30215055-378b5a06-94e1-11e7-8450-bbd711e9dc19.png)
and cannot focus on the input textbox
tested on today's nightly

**Comment by ghost** [comment]
@kkren yeas, those are known issues. Thats the best I could manage. And about the input textbox focus issue, it does take focus but the mouse pointer remains doesn't change. Try typing something after clicking on it.
